name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 30
        days-before-close: 7
        exempt-issue-labels: 'stale-exempt'
        stale-issue-message: 'Issue older than 30 days. Marking as stale. Issue will be automatically closed in 7 days.'
        stale-issue-label: 'stale-no-issue-activity'
        close-issue-label: 'stale-closed'
        days-before-pr-close: 14
        exempt-pr-labels: 'stale-exempt'
        stale-pr-message: 'PR older than 30 days. Marking as stale. PR will be automatically closed in 14 days.'
        stale-pr-label: 'stale-no-pr-activity'
        close-pr-label: 'stale-closed'
        
